theme: current
defaults:
  sender: mime_mail
  formatter: mime_mail
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  neuronet_misc:
    none:
      formatter: mime_mail
      sender: mime_mail
