smtp_on: true
smtp_host: smtp.postmarkapp.com
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: standard
smtp_username: b63fc5a8-9565-4d70-847b-43603154980d
smtp_password: b63fc5a8-9565-4d70-847b-43603154980d
smtp_from: ngg.glia@gmail.com
smtp_fromname: Neuronet
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
